### ISSUE TITLE
Change colours in line graphs on tab 1

### ISSUE THREAD

**Issue by caraconnachan** [Improvement-Service/pop_projections_shiny_tool#116]
The colours on the graph are the same as used in the map but don't correspond to what is on the map making it confusing. Would be worth changing to avoid confusion. We'll be adding a highlight colour to the selected are on the map so it would be worth matching this on the graph.

These colours are set in the line graph function so will need to be changed there.

**Comment by mairiskye** [comment]
achieved in branch for issue #115
