### ISSUE TITLE
Link council area selections on both tabs

### ISSUE THREAD

**Issue by caraconnachan** [Improvement-Service/pop_projections_shiny_tool#118]
Use an observe event to update the council selection on both pages to update whenever a selection is made. E.g. if user selects Aberdeen City on tab 1, this will population the drop down on tab 2 with Aberdeen City and vise versa.
Need to look at how this will interact with the "Submit selections" button on tab 1, e.g. if user selects new LA on tab 2, will the new selection automatically be ran on tab 1 or will users still need to select the button.

**Comment by mairiskye** [comment]
achieved in branch for issue #115
