### ISSUE TITLE
Filter data for similar areas graph - Tab 2

### ISSUE THREAD

**Issue by caraconnachan** [Improvement-Service/pop_projections_shiny_tool#30]
- Use ranked small area data set

- Store rank of selected area for selected measure

- Filter to only include area-name where rank for selected measure is +-2 from selected area rank

- Change area_name column to concatenated council name and area name (this will mean the labels for the similar areas graph show which council the area is in)

**Comment by mairiskye** [comment]
old tab 2 issue - no longer relevant
