### ISSUE TITLE
Move data computation to within renderLeaflet function

### ISSUE THREAD

**Issue by caraconnachan** [Improvement-Service/pop_projections_shiny_tool#94]
Currently for la_map_tab_1 the data is filtered and merged with the shape file before it is then called within the renderLeaflet function. However there's no need for this to be done separately therefore this code could be moved to within the renderLeaflet function.

**Comment by caraconnachan** [comment]
Some of this may have already been done in a separate issue. If so close this issue

**Comment by mairiskye** [comment]
completed in earlier branch (tab_1_plot_layout_experiment)
