### ISSUE TITLE
Run line graph function for within areas graph, tab 2 (Other Measures)

### ISSUE THREAD

**Issue by caraconnachan** [Improvement-Service/pop_projections_shiny_tool#98]
Data argument - resulting data set from previous filter
Detail arguments -
Council = council input
Small Area = small area input
Measure = measure selection
Graph Type - Within Areas

Add output to Ui

**Comment by caraconnachan** [comment]
data argument will be measures_data_tab_2

**Comment by mairiskye** [comment]
completed in issue 97 branch
